/**
 * Seller Invite Acceptance Component (Phase 13: Field Operator Invitation Activation)
 * 
 * Allows shopkeepers to claim and activate their shop using the invitation token
 * generated by the field operator during in-person onboarding.
 */

import React, { useState, useEffect } from 'react';
import {
  Store,
  ShieldCheck,
  CheckCircle2,
  AlertCircle,
  ArrowRight,
  Sparkles,
  QrCode,
  MapPin,
  Clock,
  Truck,
  Building,
} from 'lucide-react';
import { useSellerAuth } from '../../context/SellerAuthContext.tsx';
import { useSellerLanguage } from '../../context/SellerLanguageContext.tsx';
import confetti from 'canvas-confetti';

interface SellerInviteAcceptModalProps {
  initialToken?: string;
  isOpen: boolean;
  onClose: () => void;
}

export const SellerInviteAcceptModal: React.FC<SellerInviteAcceptModalProps> = ({
  initialToken = '',
  isOpen,
  onClose,
}) => {
  const { login } = useSellerAuth();
  const { language, t } = useSellerLanguage();

  const [tokenInput, setTokenInput] = useState(initialToken);
  const [invitationData, setInvitationData] = useState<any | null>(null);
  const [isLoadingDetails, setIsLoadingDetails] = useState(false);
  const [isAccepting, setIsAccepting] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [isSuccess, setIsSuccess] = useState(false);

  useEffect(() => {
    if (initialToken) {
      setTokenInput(initialToken);
      fetchInvitation(initialToken);
    }
  }, [initialToken]);

  const fetchInvitation = async (tok: string) => {
    if (!tok.trim()) return;
    setIsLoadingDetails(true);
    setError(null);
    try {
      const res = await fetch(`/api/auth/seller-invitations/${encodeURIComponent(tok.trim())}`);
      const json = await res.json();
      if (!res.ok) {
        throw new Error(json.error?.message || json.message || 'Invitation token not found or expired');
      }
      setInvitationData(json.data);
    } catch (err: any) {
      setError(err.message || 'Failed to fetch invitation details');
      setInvitationData(null);
    } finally {
      setIsLoadingDetails(false);
    }
  };

  const handleClaimShop = async () => {
    if (!tokenInput.trim()) return;
    setIsAccepting(true);
    setError(null);

    try {
      const res = await fetch('/api/auth/seller-invitations/accept', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ token: tokenInput.trim() }),
      });

      const json = await res.json();
      if (!res.ok) {
        throw new Error(json.error?.message || json.message || 'Failed to accept invitation');
      }

      // Store auth session
      if (json.data?.token) {
        localStorage.setItem('seller_auth_token', json.data.token);
        localStorage.setItem('auth_token', json.data.token);
      }
      if (json.data?.user?.id) {
        localStorage.setItem('seller_user_id', json.data.user.id);
      }
      if (json.data?.shop?.id || json.data?.user?.shopId) {
        localStorage.setItem('seller_shop_id', json.data?.shop?.id || json.data?.user?.shopId);
      }

      setIsSuccess(true);
      confetti({ particleCount: 80, spread: 70, origin: { y: 0.6 } });

      setTimeout(() => {
        // Trigger auto login into context
        window.location.reload();
      }, 1200);
    } catch (err: any) {
      setError(err.message || 'Error activating shop account');
    } finally {
      setIsAccepting(false);
    }
  };

  if (!isOpen) return null;

  return (
    <div className="fixed inset-0 z-50 bg-black/80 backdrop-blur-xs flex items-center justify-center p-4">
      <div className="bg-slate-900 border border-slate-800 rounded-3xl w-full max-w-md p-6 shadow-2xl space-y-5 animate-scale-up">
        {/* Header */}
        <div className="flex items-center justify-between pb-3 border-b border-slate-800">
          <div className="flex items-center space-x-2">
            <div className="w-8 h-8 rounded-xl bg-emerald-500/20 text-emerald-400 flex items-center justify-center font-bold">
              <QrCode className="w-4 h-4" />
            </div>
            <div>
              <h2 className="text-sm font-black text-white">
                {language === 'hi' ? 'दुकानदार आमंत्रण कोड' : 'Claim Shop by Invite'}
              </h2>
              <p className="text-[11px] text-slate-400">
                {language === 'hi' ? 'फील्ड ऑपरेटर द्वारा दिया गया टोकन दर्ज करें' : 'Enter the code provided by your field operator'}
              </p>
            </div>
          </div>

          <button
            onClick={onClose}
            className="w-7 h-7 rounded-full bg-slate-800 hover:bg-slate-700 text-slate-400 hover:text-white flex items-center justify-center text-xs"
          >
            ✕
          </button>
        </div>

        {error && (
          <div className="p-3 rounded-2xl bg-rose-950/70 border border-rose-800/80 text-rose-200 text-xs flex items-start space-x-2">
            <AlertCircle className="w-4 h-4 text-rose-400 shrink-0 mt-0.5" />
            <span>{error}</span>
          </div>
        )}

        {isSuccess ? (
          <div className="py-8 text-center space-y-3">
            <div className="w-16 h-16 rounded-full bg-emerald-500/20 text-emerald-400 flex items-center justify-center mx-auto">
              <CheckCircle2 className="w-10 h-10" />
            </div>
            <h3 className="text-lg font-black text-white">
              {language === 'hi' ? 'दुकान सक्रिय हो गई!' : 'Shop Successfully Activated!'}
            </h3>
            <p className="text-xs text-slate-300">
              {language === 'hi'
                ? 'आपका खाता सक्रिय कर दिया गया है। पोर्टल लोड हो रहा है...'
                : 'Your merchant account is now live. Redirecting to your dashboard...'}
            </p>
          </div>
        ) : (
          <div className="space-y-4">
            <div>
              <label className="block text-xs font-bold text-slate-300 mb-1.5">
                {language === 'hi' ? 'आमंत्रण टोकन (Invitation Code)' : 'Invitation Token'}
              </label>
              <div className="flex gap-2">
                <input
                  type="text"
                  placeholder="e.g. inv_1730000000_abcd"
                  value={tokenInput}
                  onChange={(e) => setTokenInput(e.target.value)}
                  className="flex-1 px-3 py-2.5 bg-slate-950 border border-slate-700 rounded-xl text-xs text-white font-mono outline-hidden focus:border-emerald-500"
                />
                <button
                  type="button"
                  onClick={() => fetchInvitation(tokenInput)}
                  disabled={isLoadingDetails || !tokenInput.trim()}
                  className="px-4 py-2.5 bg-slate-800 hover:bg-slate-700 text-slate-200 text-xs font-bold rounded-xl transition disabled:opacity-50"
                >
                  {isLoadingDetails ? 'Checking...' : 'Verify'}
                </button>
              </div>
            </div>

            {invitationData && (
              <div className="p-4 bg-slate-950/80 border border-emerald-500/30 rounded-2xl space-y-3 animate-fade-in">
                <div className="flex items-center justify-between">
                  <span className="text-[10px] font-black uppercase tracking-wider px-2 py-0.5 rounded-full bg-emerald-500/20 text-emerald-400 border border-emerald-500/30">
                    Verified Shop Invitation
                  </span>
                  <span className="text-[11px] text-slate-400 font-mono">
                    Status: {invitationData.invitation?.status}
                  </span>
                </div>

                <div className="space-y-1">
                  <h4 className="text-sm font-black text-white flex items-center gap-1.5">
                    <Store className="w-4 h-4 text-emerald-400" />
                    {invitationData.shop?.name || invitationData.invitation?.shopName}
                  </h4>
                  <p className="text-xs text-slate-400">
                    Owner: <span className="text-slate-200 font-semibold">{invitationData.invitation?.sellerName}</span> ({invitationData.invitation?.sellerPhone})
                  </p>
                  {invitationData.shop?.address && (
                    <p className="text-[11px] text-slate-400 flex items-center gap-1">
                      <MapPin className="w-3 h-3 text-slate-500" />
                      {invitationData.shop.address}
                    </p>
                  )}
                </div>

                <button
                  type="button"
                  disabled={isAccepting || invitationData.invitation?.status === 'ACCEPTED'}
                  onClick={handleClaimShop}
                  className="w-full py-3 bg-emerald-600 hover:bg-emerald-500 text-white text-xs font-black rounded-xl flex items-center justify-center gap-2 shadow-lg shadow-emerald-600/30 transition disabled:opacity-50"
                >
                  {isAccepting ? (
                    <span className="flex items-center gap-2">
                      <span className="w-3.5 h-3.5 border-2 border-white border-t-transparent rounded-full animate-spin" />
                      Activating Account...
                    </span>
                  ) : (
                    <span className="flex items-center gap-2">
                      <ShieldCheck className="w-4 h-4" /> Claim & Launch My Shop
                    </span>
                  )}
                </button>
              </div>
            )}
          </div>
        )}
      </div>
    </div>
  );
};
